accounts/urls.py
from django.urls import path
from .views import SignUpView, UserUpdate

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('user_update_profile/', UserUpdate.as_view(), name='user-update-profile'),
]

jedzonko/urls.py
from django.urls import path

from jedzonko.views import IndexView, RecipeListView, DashboardView, RecipeCreateView, PlanListView, PlanCreateView, \
    ReceipeDetailView, PlanDetailView, SchedulesMealCreateView, IngredientsCreateView, IngredientsListView, \
    RecipeUpdate, PlanUpdate, IngredientUpdate, RecipeDeleteView, PlanDeleteView, SchedulesMealCDelete

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('recipe/list', RecipeListView.as_view(), name='recipe_list'),
    path('main', DashboardView.as_view(), name='dashbord'),
    path('recipe/add/', RecipeCreateView.as_view(), name='add_recipe'),
    path('plan/list', PlanListView.as_view(), name='plan_list'),
    path('plan/add/', PlanCreateView.as_view(), name='add_plan'),
    path('recipe/<int:pk>/', ReceipeDetailView.as_view(), name='recipe_details'),
    path('plan/<int:id>/', PlanDetailView.as_view(), name='plan_details'),
    path('plan/add-recipe/', SchedulesMealCreateView.as_view(), name='add-plan-recipe'),
    path('ingredient/add/', IngredientsCreateView.as_view(), name='add_ingredient'),
    path('ingredient/', IngredientsListView.as_view(), name='ingredient'),
    path('recipe/modify/<int:pk>/', RecipeUpdate.as_view(), name='update_recipe'),
    path('plan/modify/<int:pk>/', PlanUpdate.as_view(), name='update_plan'),
    path('ingredient/modify/<int:pk>/', IngredientUpdate.as_view(), name='update_ingredient'),
    path('recipe/del/<int:id>/', RecipeDeleteView.as_view(), name='delete_recipe'),
    path('plan/del/<int:id>/', PlanDeleteView.as_view(), name='delete_plan'),
    path('plan_recipe/del/<int:pk>/', SchedulesMealCDelete.as_view(), name='delete_schedules'),


]

scrumlab/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jedzonko.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jedzonko/models.py
from django.contrib.auth.models import User
from django.db import models


class Ingredients(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Receipe(models.Model):
    name = models.CharField(max_length=255)
    ingredients = models.ManyToManyField(Ingredients)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    preparation_time = models.IntegerField()
    votes = models.IntegerField(default=0)
    method_preparation = models.TextField(null=True)
    recipe_image= models.ImageField(upload_to='recipe/',blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Plan(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    recipes = models.ManyToManyField(Receipe, through='Recipeplan')
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_recepis(self):
        days = Dayname.objects.order_by('order')
        lst = []
        for day in days:
            lst.append(self.get_meals_for_day(day))
        return lst

    def get_meals_for_day(self, day_id):
        rp = Recipeplan.objects.filter(day_name=day_id, plan=self).order_by('order')
        return rp



class Dayname(models.Model):
    day_name = models.CharField(max_length=16)
    order = models.IntegerField(unique=True)

    def __str__(self):
        return self.day_name


class Mealname(models.Model):
    meal_name = models.CharField(max_length=255)

    def __str__(self):
        return self.meal_name


class Recipeplan(models.Model):
    meal_name = models.CharField(max_length=255)
    order = models.IntegerField()
    day_name = models.ForeignKey(Dayname, on_delete=models.CASCADE, related_name='dayname_recipplan')
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE, related_name='plan_recipplan')
    recipe = models.ForeignKey(Receipe, on_delete=models.CASCADE, related_name='recipe_reciplan')

    def __str__(self):
        return f'{self.meal_name}-{self.day_name}'

jedzonko/forms.py
from urllib import request

from django import forms

from jedzonko.models import Receipe, Plan, Recipeplan, Ingredients


class ReceipeForm(forms.ModelForm):
    class Meta:
        model= Receipe
        fields = ['name','ingredients','description','preparation_time','method_preparation','recipe_image']

class PlanForm(forms.ModelForm):
    class Meta:
        model= Plan
        fields = ['name','description']

class SchedulesMealForm(forms.ModelForm):
    class Meta:
        model = Recipeplan
        fields = ['meal_name','order','day_name','plan','recipe']

    # def __init__(self, user=None, **kwargs):
    #     super(SchedulesMealForm, self).__init__(**kwargs)
    #     if user:
    #         self.fields['plan'].queryset = Plan.objects.filter(owner=user)



class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredients
        fields = ['name']

jedzonko/views.py
from datetime import datetime
import random
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from jedzonko.forms import ReceipeForm, PlanForm, SchedulesMealForm, IngredientForm

from jedzonko.models import Receipe, Plan, Dayname, Recipeplan, Ingredients


class IndexView(View):
    def get(self, request):
        recipe_list = list(Receipe.objects.all())
        random.shuffle(recipe_list)
        carusel_active =recipe_list[0]
        recipe_shuffle = recipe_list[1:3]
        return render(request, "jedzonko/index.html", {'recipe_shuffle':recipe_shuffle,'carusel_active':carusel_active})

class RecipeListView(View):
    def get(self, request):
        recipe_list = Receipe.objects.order_by("votes")
        return render(request, "jedzonko/app-recipes.html", {'recipe_list': recipe_list})

class DashboardView(LoginRequiredMixin,View):
    def get(self,request):
        count_receipe = Receipe.objects.count()
        count_plans = Plan.objects.count()
        plan_exist= Plan.objects.filter(owner=request.user)
        last_plan = plan_exist.last()
        return render(request,'jedzonko/dashboard.html',{'count_receipe':count_receipe,'count_plans':count_plans,'last_plan':last_plan,'plan_exist':plan_exist})



class RecipeCreateView(LoginRequiredMixin,CreateView):
    form_class = ReceipeForm
    success_url = reverse_lazy('recipe_list')
    template_name = 'jedzonko/app-add-recipe.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.GET.get('next', self.success_url)


class RecipeUpdate(LoginRequiredMixin,UpdateView):
    model = Receipe
    form_class = ReceipeForm
    template_name = 'jedzonko/app-edit-recipe.html'
    success_url = reverse_lazy('recipe_list')

    def user_passes_test(self, request):
        if request.user.is_authenticated:
            self.object = self.get_object()
            return self.object.owner == request.user
        return False

    def dispatch(self, request, *args, **kwargs):
        if not self.user_passes_test(request):
            return redirect('dashbord')
        return super(RecipeUpdate, self).dispatch(
            request, *args, **kwargs)


class RecipeDeleteView(LoginRequiredMixin, View):
    def get(self, request, id):
        receipe = Receipe.objects.get(pk=id)
        if receipe.owner == request.user:
            receipe_del = Receipe.objects.get(pk=id)
            return render(request, 'jedzonko/app-del-recipe.html', {'receipe_del': receipe_del})
        else:
            return redirect('home')

    def post(self, request, id):
        receipe = Receipe.objects.get(pk=id)
        receipe.delete()
        return redirect('recipe_list')


class PlanListView(LoginRequiredMixin,View):
    def get(self, request):
        plan_list = Plan.objects.filter(owner=request.user).order_by('name')
        return render(request, "jedzonko/app-schedules.html", {'plan_list': plan_list})

# class PlanCreateView(CreateView):
#     form_class = PlanForm
#     success_url = reverse_lazy('plan_list')
#     template_name = 'jedzonko/app-add-schedules.html'
#

class PlanCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = PlanForm()
        return render(request, 'jedzonko/app-add-schedules.html',
                      {'form': form})

    def post(self, request):
        planForm = PlanForm(request.POST, request.FILES)
        if planForm.is_valid():
            plan = planForm.save(commit=False)
            plan.owner = request.user
            plan.save()
        return redirect('plan_list')

class PlanUpdate(LoginRequiredMixin,UpdateView):
    model = Plan
    form_class = PlanForm
    template_name = 'jedzonko/app-edit-schedules.html'
    success_url = reverse_lazy('plan_list')

    def user_passes_test(self, request):
        if request.user.is_authenticated:
            self.object = self.get_object()
            return self.object.owner == request.user
        return False

    def dispatch(self, request, *args, **kwargs):
        if not self.user_passes_test(request):
            return redirect('dashbord')
        return super(PlanUpdate, self).dispatch(
            request, *args, **kwargs)

class PlanDeleteView(LoginRequiredMixin, View):
    def get(self, request, id):
        plan = Plan.objects.get(pk=id)
        if plan.owner == request.user:
            plan_del = Plan.objects.get(pk=id)
            return render(request, 'jedzonko/app-del-plan.html', {'plan_del': plan_del})
        else:
            return redirect('home')

    def post(self, request, id):
        plan = Plan.objects.get(pk=id)
        plan.delete()
        return redirect('plan_list')

class ReceipeDetailView(DetailView):
    model = Receipe
    template_name = 'jedzonko/app-recipe-details.html'
    pk_url_kwarg = 'pk'


class PlanDetailView(View):
    def get(self,request,id):
        plan = Plan.objects.get(id=id)
        days_in_week = Dayname.objects.order_by("order")
        ret_val = []
        for day in days_in_week:
            temp = Recipeplan.objects.filter(day_name_id=day, plan_id=plan).order_by('order')
            ret_val.append(temp)
            return render(request, 'jedzonko/app-details-schedules.html',
                          {'recepi_plan': ret_val, 'plan': plan, 'days_in_week': days_in_week})


class SchedulesMealCreateView(CreateView):
    form_class = SchedulesMealForm
    success_url = reverse_lazy('add-plan-recipe')
    template_name = 'jedzonko/app-schedules-meal-recipe.html'

class SchedulesMealCDelete(DeleteView):
    model = Recipeplan
    template_name = 'jedzonko/app-del-schedules.html'
    success_url = reverse_lazy('dashbord')




# class SchedulesMealCreateView(LoginRequiredMixin, View):
#     def get(self, request):
#         form = SchedulesMealForm(user=request.user)
#         return render(request, 'jedzonko/app-schedules-meal-recipe.html',
#                       {'form': form})
#
#     def post(self, request):
#         plansForm = SchedulesMealForm(request.POST)
#         if plansForm.is_valid():
#             plans = plansForm.save(commit=False)
#             plans.save()
#             plansForm.save_m2m()
#         return redirect('add-plan-recipe')


class IngredientsCreateView(LoginRequiredMixin,CreateView):
    form_class = IngredientForm
    success_url = reverse_lazy('add_ingredient')
    template_name = 'jedzonko/app-add-ingredient.html'

class IngredientUpdate(LoginRequiredMixin,UpdateView):
    model = Ingredients
    form_class = IngredientForm
    template_name = 'jedzonko/apo-edit-ingredients.html'
    success_url = reverse_lazy('ingredient')


class IngredientsListView(ListView):
    paginate_by = 50
    template_name = 'jedzonko/app-ingredients.html'
    model = Ingredients

jedzonko/templates/jedzonko/apo-edit-ingredients.html
{% extends "__base__.html" %}
{% block content %}

<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">NOWY SKŁADNIK</h3>
        </div>
    <form action="" method="post" >
                {% csrf_token %}
        <div class="col d-flex justify-content-end mb-2 noPadding">
            <input type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-40" value="Zapisz">

        </div>
    </div>

    <div class="schedules-content">

            <div class="form-group row">
                <label for="planName"
                       class="col-sm-2 label-size col-form-label">
                    Edytuj Składnik
                </label>
                <div class="col-sm-10">
                    <input type="text" class="form-control"
                           name="name" maxlength="255" required id="id_name" value="{{ ingredients.name }}">
                </div>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock content %}

{% block title %}{% endblock %}

jedzonko/templates/jedzonko/app-add-ingredient.html
{% extends "__base__.html" %}
{% block content %}

<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">NOWY SKŁADNIK</h3>
        </div>
    <form action="" method="post" >
                {% csrf_token %}
        <div class="col d-flex justify-content-end mb-2 noPadding">
            <input type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-40" value="Zapisz">

        </div>
    </div>

    <div class="schedules-content">

            <div class="form-group row">
                <label for="planName"
                       class="col-sm-2 label-size col-form-label">
                    Nazwa planu
                </label>
                <div class="col-sm-10">
                    <input type="text" class="form-control"
                           placeholder="Nazwa składnika" name="name" maxlength="255" required id="id_name">
                </div>
            </div>
        </form>
    </div>
</div>

</div>
{% endblock content %}

{% block title %}{% endblock %}

jedzonko/templates/jedzonko/app-add-recipe.html
{% extends "__base__.html" %}

{% block title %}Nowy przepis{% endblock %}

{% block content %}


<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <form class="mt-4 ml-4 mr-4" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row border-bottom border-3">
            <div class="col"><h3 class="color-header text-uppercase">Nowy
                przepis</h3></div>

            <div class="col d-flex justify-content-end mb-2">
                <button type="submit"
                        class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">
                    Zapisz
                </button>
            </div>
        </div>

        <table class="table borderless">
            <tbody>
            <tr class="d-flex">
                <th scope="row" class="col-2">Nazwa Przepisu</th>
                <td class="col-7">
                    <input class="w-100 p-1" name="name" required id="id_name" value="">
                </td>
            </tr>
            <tr class="d-flex">
                <th scope="row" class="col-2">Opis przepisu</th>
                <td class="col-7"><textarea name="description"  required id="id_description" class="w-100 p-1"
                                            rows="5"></textarea></td>
            </tr>
            <tr class="d-flex">
                <th scope="row" class="col-2">Przygotowani(minuty)</th>
                <td class="col-3">
                    <input class="p-1" type="number" name="preparation_time" required id="id_preparation_time" value="">
                </td>
            </tr>
            </tbody>
        </table>

        <div class="row d-flex">
            <div class="col-5 border-bottom border-3"><h3
                    class="text-uppercase">Sposób przygotowania</h3></div>
            <div class="col-2"></div>
            <div class="col-5 border-bottom border-3"><h3
                    class="text-uppercase">Składniki</h3></div>
        </div>
        <div class="row d-flex">
            <div class="col-5 p-4">
                <textarea name="method_preparation" class="w-100 p-1" rows="10"></textarea>
            </div>
            <div class="col-2"></div>

            <div class="col-5 p-4">
                {{ form.ingredients }}
            </div>
            <p><label for="id_recipe_image">Zdjęcie:</label> <input type="file" name="recipe_image" accept="image/*" id="id_recipe_image"></p>
        </div>
    </form>
    </div>

{% endblock content %}

jedzonko/templates/jedzonko/app-add-schedules.html
{% extends "__base__.html" %}
{% block content %}

<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">NOWY PLAN</h3>
        </div>
    <form action="" method="post" >
                {% csrf_token %}
        <div class="col d-flex justify-content-end mb-2 noPadding">
            <input type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-40" value="Zapisz">

        </div>
    </div>

    <div class="schedules-content">

            <div class="form-group row">
                <label for="planName"
                       class="col-sm-2 label-size col-form-label">
                    Nazwa planu
                </label>
                <div class="col-sm-10">
                    <input type="text" class="form-control"
                           placeholder="Nazwa planu" name="name" maxlength="255" required id="id_name">
                </div>
            </div>
            <div class="form-group row">
                <label for="planDescription"
                       class="col-sm-2 label-size col-form-label">
                    Opis planu
                </label>
                <div class="col-sm-10">
                    <textarea class="form-control" rows="5"
                              placeholder="Opis planu" name="description" required id="id_description"></textarea>
                </div>
            </div>
        </form>
    </div>
</div>

</div>
{% endblock content %}

{% block title %}{% endblock %}

jedzonko/templates/jedzonko/app-del-plan.html
{% extends '__base__.html' %}

{% block content %}
    <br>

    <h3>Czy napewno chcesz usunąć plan numer {{ plan_del.id }} ???</h3>
    <br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p> {{ plan_del.name }}</p>
        <br>

        <input class="btn btn-danger" type="submit" value="Tak - usuń"/>
    </form>
    <br>
    <a href=" {% url 'plan_list' %}  ">
        <button type="button" class="btn btn-success">Nie - wróc do moich planów</button>
    </a>
{% endblock %}

jedzonko/templates/jedzonko/app-del-recipe.html
{% extends '__base__.html' %}

{% block content %}
    <br>

    <h3>Czy napewno chcesz usunąć przepis numer {{ receipe_del.id }} ???</h3>
    <br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p> {{ receipe_del.name }}</p>
        <br>

        <input class="btn btn-danger" type="submit" value="Tak - usuń"/>
    </form>
    <br>
    <a href=" {% url 'recipe_list' %}  ">
        <button type="button" class="btn btn-success">Nie - wróc do moich przepisów</button>
    </a>
{% endblock %}

jedzonko/templates/jedzonko/app-edit-recipe.html
{% extends "__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}
<div class="dashboard-content border-dashed p-3 m-4 view-height">
<form action="" method="post" enctype="multipart/form-data">
     {% csrf_token %}
    <div class="mt-4 ml-4 mr-4">
        <div class="row border-bottom border-3">
            <div class="col"><h3 class="color-header text-uppercase">Edycja
                przepisu</h3></div>
            <div class="col d-flex justify-content-end mb-2">
                <button type="submit"
                        class="btn btn-color rounded-0 pt-0 pb-0 pr-4 pl-4">
                    Zapisz
                </button>
            </div>
        </div>

        <table class="table borderless">
            <tbody>
            <tr class="d-flex">
                <th scope="row" class="col-2">Nazwa Przepisu</th>
                <td class="col-7">
                    <input class="w-100 p-1" name="name"  value="{{ receipe.name }}"  required id="id_name">
                </td>
            </tr>
            <tr class="d-flex">
                <th scope="row" class="col-2">Opis przepisu</th>
                <td class="col-7"><textarea name="description" class="w-100 p-1" rows="5" required id="id_description">{{ receipe.description }} </textarea>
                </td>
            </tr>
            <tr class="d-flex">
                <th scope="row" class="col-2">Przygotowani(minuty)</th>
                <td class="col-3">
                    <input class="p-1" type="number" name="preparation_time" required id="id_preparation_time" value="{{ receipe.preparation_time }}">
                </td>
            </tr>
            </tbody>
        </table>

        <div class="row d-flex">
            <div class="col-5 border-bottom border-3"><h3
                    class="text-uppercase">Sposób przygotowania</h3></div>
            <div class="col-2"></div>
            <div class="col-5 border-bottom border-3"><h3
                    class="text-uppercase">Składniki</h3></div>
        </div>
        <div class="row d-flex">
            <div class="col-5 p-4">
                <textarea class="w-100 p-1" rows="10" name="method_preparation" required id="id_method_preparation">{{ receipe.method_preparation }}</textarea>
            </div>
            <div class="col-2"></div>

            <div class="col-5 p-4">





{{ form.ingredients }}

            </div>
            <p><label for="id_recipe_image">Zdjęcie:</label> Teraz: <a href="{{ receipe.recipe_image.url }}">{{ receipe.recipe_image.url }}</a>
<input type="checkbox" name="recipe_image-clear" id="recipe_image-clear_id">
<label for="recipe_image-clear_id">Wyczyść</label><br>
Zmień:
<input type="file" name="recipe_image" accept="image/*" id="id_recipe_image"></p>
        </div>
    </div>
</form>
{#<form action="" method="post" enctype="multipart/form-data">#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" value="Wyślij">#}
{#</form>#}
</div>
{% endblock content %}

jedzonko/templates/jedzonko/app-edit-schedules.html
{% extends "__base__.html" %}
{% block title %}{% endblock title %}
{% block content %}
<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">EDYTUJ PLAN</h3>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <div class="col d-flex justify-content-end mb-2 noPadding">
            <input type="submit" value="Zapisz" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">
        </div>
    </div>

    <div class="schedules-content">

            <div class="form-group row">
                <label for="planName"
                       class="col-sm-2 label-size col-form-label">
                    Nazwa planu
                </label>
                <div class="col-sm-10">
                    <input class="form-control" name="name"
                           value="{{ plan.name }}"
                           required id="id_name" placeholder="Nazwa planu">
                </div>
            </div>
            <div class="form-group row">
                <label for="planDescription"
                       class="col-sm-2 label-size col-form-label">
                    Opis planu
                </label>
                <div class="col-sm-10">
                                    <textarea class="form-control" rows="5"
                                              required id="id_description" name="description"
                                              placeholder="Opis plany">{{ plan.description }}
                                    </textarea>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

jedzonko/templates/jedzonko/app-ingredients.html
{% extends "__base__.html" %}
{% block title %}{% endblock %}
{% block content %}
<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">LISTA SKŁADNIKÓW</h3>
        </div>
        <div class="col d-flex justify-content-end mb-2 noPadding">
            <a href="{% url 'add_ingredient' %}"
               class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4">Dodaj
                składnik</a>
        </div>
    </div>

    <div class="schedules-content">
        <table class="table border-bottom">
            <thead>
            <tr class="d-flex">
                <th class="col-1">ID</th>
                <th class="col-2">NAZWA</th>
                <th class="col-2 center">AKCJE</th>
            </tr>
            </thead>
            <tbody class="text-color-lighter">
            {% for ingredient in object_list %}
            <tr class="d-flex">

                <td class="col-1">{{ ingredient.id }}</td>
                <td class="col-2">{{ ingredient.name }}</td>
                <td class="col-2 d-flex align-items-center justify-content-center flex-wrap">
                    <a href="{% url 'update_ingredient' ingredient.pk %}"
                       class="btn btn-warning rounded-0 text-light m-1">Edytuj</a>
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

jedzonko/templates/jedzonko/app-schedules-meal-recipe.html
{% extends "__base__.html" %}
{% block title %}{% endblock %}
{% block content %}
    <style>
    select {
        width: 500px;
    }

    </style>
<div class="dashboard-content border-dashed p-3 m-4 view-height">
    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">DODAJ PRZEPIS DO PLANU</h3>
        </div>

        <div class="col d-flex justify-content-end mb-2 noPadding">
            <form action="" method="post" >
            {% csrf_token %}
            <input type="submit" class="btn btn-success rounded-0 pt-0 pb-0 pr-4 pl-4" value="Wyślij">
        </div>
    </div>

    <div class="schedules-content">

            <div class="form-group row">
                <label for="choosePlan"
                       class="col-sm-2 label-size col-form-label">
                    Wybierz plan
                </label>
                <div class="col-sm-3">
                    {{ form.plan }}
                </div>
            </div>
            <div class="form-group row">
                <label for="name" class="col-sm-2 label-size col-form-label">
                    Nazwa posiłku
                </label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" value="" id="id_meal_name" name="meal_name"
                           placeholder="Nazwa posiłku" style="width: 500px">
                </div>
            </div>
            <div class="form-group row">
                <label for="number" class="col-sm-2 label-size col-form-label">
                    Numer posiłku
                </label>
                <div class="col-sm-2">
                    <input type="number" class="form-control" value="" id="id_order" name="order"
                           placeholder="Numer posiłku" style="width: 500px">
                </div>
            </div>
            <div class="form-group row">
                <label for="recipie" class="col-sm-2 label-size col-form-label">
                    Przepis
                </label>
                <div class="col-sm-4 ">
                <div >{{ form.recipe }}</div>

                </div>
            </div>
            <div class="form-group row">
                <label for="day" class="col-sm-2 label-size col-form-label">
                    Dzień
                </label>
                <div class="col-sm-2">
                   <div>{{ form.day_name }}</div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock content %}